# Generated by Django 3.1 on 2020-09-09 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccess',
            name='confirm_password',
        ),
    ]
