# Generated by Django 3.1 on 2020-08-31 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password1',
            field=models.CharField(max_length=15),
        ),
    ]
