# Generated by Django 3.1.1 on 2020-09-04 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0003_auto_20200903_1140'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserAccess',
        ),
    ]
