# Generated by Django 3.1.1 on 2020-09-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('event_time', models.CharField(choices=[('Morning', 'Morning'), ('Midmorning', 'Midmorning'), ('Afternoon', 'Afternoon')], default='Morning', max_length=15)),
                ('speaker', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=300)),
                ('roomcapacity', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='C:/Users/user.CAMIL/Desktop/capstone_project/eventapp/backend/event/download.jpg', upload_to='uploads/')),
            ],
        ),
    ]
