# Generated by Django 3.1.1 on 2020-09-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20200919_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='roomcapacity',
            field=models.IntegerField(max_length=50),
        ),
    ]
