# Generated by Django 3.1.1 on 2020-09-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20200922_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='roomcapacity',
            field=models.IntegerField(),
        ),
    ]
