# Generated by Django 3.1.1 on 2020-09-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20200922_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='tag_line',
            field=models.TextField(default=False),
        ),
    ]
