# Generated by Django 3.1 on 2020-09-15 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0002_auto_20200915_1559'),
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(choices=[('Morning', 'Morning'), ('Midmorning', 'Midmorning'), ('Afternoon', 'Afternoon')], default='', max_length=50, verbose_name='time')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booked', to='usermanagement.useraccess')),
            ],
        ),
    ]
