# Generated by Django 3.1 on 2020-09-18 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventbooking', '0006_auto_20200917_1812'),
        ('eventbooking', '0004_auto_20200916_0800'),
    ]

    operations = [
    ]
