# Generated by Django 3.1.1 on 2020-09-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventbooking', '0007_merge_20200918_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date_registered',
            field=models.DateField(blank=True, null=True),
        ),
    ]
