# Generated by Django 3.1.1 on 2020-09-23 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventbooking', '0008_booking_date_registered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
